### ISSUE TITLE
在quform下选择zip格式的内容无法正常上传到阿里oss

### ISSUE THREAD

**Issue by mengyaoren** [sy-records/aliyun-oss-wordpress#11]
选择图片可以正常使用，如果没启用插件，zip 格式也能正常传到 uploads
![Xnip2022-07-09_23-47-57](https://user-images.githubusercontent.com/726165/178112944-05615307-dd09-4272-aa9c-60029bdaa4f1.jpg)
![Xnip2022-07-09_23-48-25](https://user-images.githubusercontent.com/726165/178112951-1a8086f5-ab3e-48e9-a8c4-1fb1eea39183.jpg)

**Comment by sy-records** [comment]
只支持从媒体库上传

**Comment by mengyaoren** [comment]
ok

**Comment by mengyaoren** [comment]
请问有计划支持吗？没有的话我就想别的办法了。

**Comment by mengyaoren** [comment]
@sy-records

**Comment by sy-records** [comment]
oss开启回源配置
