### ISSUE TITLE
开启插件后上传大文件有问题

### ISSUE THREAD

**Issue by liufuli0321** [sy-records/aliyun-oss-wordpress#12]
有个问题，我想上传较大的PDF，插件配置好禁用后，上传一个22M的pdf可以正常上传到服务器并在媒体库显示，OSS不会上传
插件启用后，同样的文件上传会报错，提示如下，实际上服务器里面已经有了，但是oss没有也不会在媒体库显示。
![image](https://user-images.githubusercontent.com/18660002/222990829-266f3454-76cf-4476-a491-0463f6422cd5.png)

**Comment by liufuli0321** [comment]
wordpress是6.1.1版本，开启了镜像回源

**Comment by sy-records** [comment]
跟服务器配置有些关系，所以可能会出现失败的情况，可以尝试走内网。或者开启回源，配置好就行
