### ISSUE TITLE
媒体库删除图片，OSS上没有同步删除

### ISSUE THREAD

**Issue by TrueSaveWorldPig** [sy-records/aliyun-oss-wordpress#28]

**Comment by sy-records** [comment]
没改过删除逻辑，打开debug看看有没有错误信息。

**Comment by TrueSaveWorldPig** [comment]
上传附件触发同步oss接口了<img width="1836" alt="image" src="https://github.com/sy-records/aliyun-oss-wordpress/assets/55381817/08004137-0b7f-4760-be63-1388eee9abd1">
我点击永久删除，却没有触发任何接口
<img width="1698" alt="image" src="https://github.com/sy-records/aliyun-oss-wordpress/assets/55381817/5c5cee27-2da3-412a-9052-c489e0199d3b">

**Comment by TrueSaveWorldPig** [comment]
看到控制台很多报错<img width="1694" alt="image" src="https://github.com/sy-records/aliyun-oss-wordpress/assets/55381817/b0b1c74f-94b6-4d3a-919c-3c31201a9943">

**Comment by sy-records** [comment]
debug打开看看...

**Comment by TrueSaveWorldPig** [comment]
<img width="1079" alt="image" src="https://github.com/sy-records/aliyun-oss-wordpress/assets/55381817/9bc25503-05b8-4a70-b77a-0eaeeb519b1d">
只有这些信息

**Comment by sy-records** [comment]
wp哪个版本？

**Comment by TrueSaveWorldPig** [comment]
6.4.2

**Comment by sy-records** [comment]
没复现。
<img width="545" alt="image" src="https://github.com/sy-records/aliyun-oss-wordpress/assets/33931153/c90bebea-0a81-4fca-b21f-22b3f2f63133">

**Comment by TrueSaveWorldPig** [comment]
我的oss库图片还在

**Comment by sy-records** [comment]
QQ交流群：887595381 加群私聊我帮你看看吧

**Comment by esncy** [comment]
我的也是一样的问题。
wp6.6.2
wposs1.4.20

**Comment by sy-records** [comment]
@esncy 修改`wp-config.php`，打开 `WP_DEBUG`，重新操作后查看`wp-content/debug.log`日志信息。

```php
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);
```
