### ISSUE TITLE
上传文件提示报错

### ISSUE THREAD

**Issue by Tommy-yuan** [sy-records/aliyun-oss-wordpress#3]
上传文件提示如下错误：
Notice: Undefined index: tiff|tif in /usr/local/src/huntsman/wordpress/wp-content/plugins/aliyun-oss-wordpress-1.2.2/aliyun-oss-wordpress.php on line 160

但是文件最后上传是成功的

**Comment by sy-records** [comment]
你WordPress那个版本呢

**Comment by Tommy-yuan** [comment]
5.5.1

**Comment by sy-records** [comment]
那不应该，5.5.1 这里是有的 https://github.com/WordPress/wordpress-develop/blob/5.5.1/src/wp-includes/functions.php#L3066

可以忽略这个，只是一个提示，因为你打开了PHP错误提示
