### ISSUE TITLE
勾选不在本地保留备份后，获取不到非图片格式文件大小

### ISSUE THREAD

**Issue by Andowa** [sy-records/aliyun-oss-wordpress#32]
您好，请问使用oss插件后，上传附件不显示文件大小是什么问题呢？(只是图片会显示大小，其他附件，比如：压缩包，视频文件，音频文件都不会显示大小)。
截图如下：
【图片显示大小】
<img width="417" alt="f44bee1335f11c284799b8f961ad55a8" src="https://github.com/sy-records/aliyun-oss-wordpress/assets/49613758/9caf0aed-10d8-41ca-891e-774b5cc0c9b4">

【视频不显示大小】
<img width="408" alt="692ba4f043d3a23ee3a4d6e9daef5b7f" src="https://github.com/sy-records/aliyun-oss-wordpress/assets/49613758/a3e7fdd0-da89-4d97-b536-3ea87c33fb36">

**Comment by sy-records** [comment]
没注意过，晚点测试下

**Comment by sy-records** [comment]
没复现

![image](https://github.com/sy-records/aliyun-oss-wordpress/assets/33931153/c3825d9b-935b-41d3-b385-fa508e4b6813)

**Comment by Andowa** [comment]
抱歉，没看消息。这个问题的触发条件是不勾选本地备份，如果勾选了本地备份就能显示了。可以烦请大佬再看看嘛？不知道这个算不算bug，因为网站有些特殊需求，不能开本地备份。
![image](https://github.com/sy-records/aliyun-oss-wordpress/assets/49613758/830dfcb8-2f44-4e95-a279-edb1787e923d)

**Comment by sy-records** [comment]
@Andowa 可以测试一下 #33 的代码了

**Comment by Andowa** [comment]
> @Andowa 可以测试一下 #33 的代码了

嗯，可以正常读取非图片附件的大小了，感谢！
