### ISSUE TITLE
通过woocommerce API创建产品时,wp_attachment_is_image无法检测到图片

### ISSUE THREAD

**Issue by jgarrick1992** [sy-records/aliyun-oss-wordpress#37]
问题描述
   接口返回 woocommerce_product_invalid_image_id 报错

1.图片实际已经上传成功至OSS
2.Wordpress Media 中可以查看到图片并且可以正常访问
3. 但是wp_attachment_is_image无法检测到图片存在

                                if ( ! wp_attachment_is_image( $attachment_id) ) {
                                        /* translators: %s: image ID */
                                        throw new WC_REST_Exception( 'woocommerce_product_invalid_image_id', sprintf( __( '#%s is an invalid image ID.', 'woocommerce' ), $attachment_id ), 400 );
                                }

**Comment by sy-records** [comment]
你是不是没在本地保留文件？

**Comment by jgarrick1992** [comment]
对的，没在本地留，但是在本地不留保存的情况下上传，大概有20%机率可能会成功，就有点奇怪。
我开始以为上传是异步操作，而有些图片比较小，所以会小概率上传成功，所以我就在 if ( ! wp_attachment_is_image( $attachment_id) ) 前面加个sleep，但是问题依旧。

感谢☺️，我先自己测试一下。

**Comment by sy-records** [comment]
上传都是到本地，然后再上传oss，如果不在本地保存，再删掉本地的

**Comment by jgarrick1992** [comment]
你这么说，这个表象就能解释的通了， 那小概率成功的情况应该是图片过大，本地还没有来得及删除。
我测试完给你反馈下情况。
感谢 抱拳

**Comment by sy-records** [comment]
@jgarrick1992 怎么样？

**Comment by jgarrick1992** [comment]
@sy-records so sorry. 忘记给你回复了，可以了。非常感谢
