### ISSUE TITLE
插件不替换图片处理得变量名

### ISSUE THREAD

**Issue by idevly** [sy-records/aliyun-oss-wordpress#4]
图片处理处填写如下：
```bash
?x-oss-process=style/!stylename
```
实际上这个`!stylename`最终也作为url的一部分了。
![image](https://user-images.githubusercontent.com/9484545/133869096-bb819ac1-6ca1-43d7-a5e5-893827a2a5fc.png)
![image](https://user-images.githubusercontent.com/9484545/133869103-9ff71865-8c85-4c71-8f5b-51ca9c698fcf.png)

**Comment by sy-records** [comment]
你用错了，你分隔符是`!`，规则名是`stylename`，就填`!stylename`。 而不是`?x-oss...`

**Comment by idevly** [comment]
我试了一下，只有填入`!thumbnail`才能正常显示，填入`!stylename`或者`! medium_large`都不显示，这里我的理解`!stylename`应该是个变量才对，针对不同的地方，这个名字需要根据不同的参数来显示不同尺寸的图片。

**Comment by sy-records** [comment]
对啊 - -。 根据你自己的命名填入，这里只是个示例

https://github.com/sy-records/aliyun-oss-wordpress/blob/a2725b1f67a841b8dfd0689779c7e51b1dfa0d75/aliyun-oss-wordpress.php#L647-L653

**Comment by idevly** [comment]
之前一直在用`aliyun-oss-support`，从这个插件的操作上来说，您的这款插件大约有以下几点问题：
1、即使我关闭了裁剪，依旧会生成并上传缩略图。
2、stylename并不是随着场景去改变，比如特色图片、文章内图片、媒体页面的图片都是不同的尺寸，但是该插件只能设置一种实现。
3、开启图片服务后，在文章页的URL还是原始的URL，但是在访问的时候会替换为图片规则，这样就会有一个问题，在文章编辑页是看不到图片的，只有发布以后，在前台页面才会看到。即使我将图片的url在编辑文章中将url修改为`1.png!thumbnail`,在前台页面现实的时候又会加上插件中配置的`!thumbnail`，这一块体验确实不太好。

这个是我目前遇到的一些问题，如果是我配置有问题，还望指出。

**Comment by sy-records** [comment]
裁剪不是插件控制的，这是wp的机制哈

图片处理这个确实，因为每个主题的特色图片之类的可能不一样，所以没有处理，只是处理了文章内容的。

第3个我确认下，我记得我加过判断了

**Comment by idevly** [comment]
嗯嗯，剪裁这个我看`aliyun-oss-support`这个插件特殊处理过，不会上传。您也可以参考一下把这个逻辑加进去，这个的确是wordpress修改过上传机制导致的问题。

**Comment by sy-records** [comment]
https://github.com/sy-records/aliyun-oss-wordpress/releases/tag/v1.2.8 重复添加的发版本了
