### ISSUE TITLE
v1.4.15 v1.4.16 兩個版本圖片上傳失敗

### ISSUE THREAD

**Issue by zengjunlin2022** [sy-records/aliyun-oss-wordpress#41]
v1.4.15、v1.4.16 兩個版本圖片上傳失敗
版本回退到 v1.4.14後上傳圖片正常
WordPress
WordPress 6.6.1 & PHP 8.3

**Comment by sy-records** [comment]
这两个版本升级了签名的方式，可以修改`wp-config.php`，打开 `WP_DEBUG`，重新操作后查看`wp-content/debug.log`日志信息。

```php
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);
```
