### ISSUE TITLE
设置后，上传图片不成功

### ISSUE THREAD

**Issue by gitzaai** [sy-records/aliyun-oss-wordpress#5]
设置如图所示，在wp上传附件后，oss那边都没有文件
环境lemp ，WordPress 5.8.1，php版本：7.4
![GitHub Logo](https://imgoss.gitzaai.com/wp-content/uploads/Snipaste_2021-09-28_23-01-53.png)

**Comment by sy-records** [comment]
打开wpdebug 上传查看错误信息

**Comment by AydenZ** [comment]
@gitzaai  遇到和你一样的问题，解决了吗？

**Comment by gitzaai** [comment]
> @gitzaai 遇到和你一样的问题，解决了吗？

我改用作者的COS了，应该是需要设置回源吧。

**Comment by sy-records** [comment]
媒体库上传图片失败，打开WP_DEBUG查看错误信息。
媒体库图片不显示，访问图片查看报错信息。
