### ISSUE TITLE
希望添加自定义EndPoint或者在区域选择中增加传输加速支持

### ISSUE THREAD

**Issue by Sorkai** [sy-records/aliyun-oss-wordpress#7]
![image](https://user-images.githubusercontent.com/35844770/153324296-fdf4f393-3547-4ff6-8a25-0adec30047f4.png)

**Comment by sy-records** [comment]
已添加

https://github.com/sy-records/aliyun-oss-wordpress/blob/5c1d7d09b6a6ffb48e1abbbb33893cb8669fe0d3/aliyun-oss-wordpress.php#L564-L565
