### ISSUE TITLE
这个有脚本安装的方法吗？

### ISSUE THREAD

**Issue by cyl33922073** [sy-records/aliyun-oss-wordpress#9]
你好，我们想找一个能够自动化配置的方法，这样可以一口气把ECS OSS都配置好。

**Comment by sy-records** [comment]
安装插件？还是配置一个新的ECS服务，再安装一套WordPress系统和插件？

**Comment by cyl33922073** [comment]
ecs创建 wordpress安装 本来就可以脚本化了

插件如果也能脚本安装和配置就可以了。

**Comment by sy-records** [comment]
可以使用 wp-cli 来进行安装插件，配置应该是不行的

**Comment by cyl33922073** [comment]
这样啊

沈唁 ***@***.***> 于2022年4月8日周五 17:15写道：
